POST http://localhost/api/login
Content-Type: application/json

{
"username": "admin",
"password": "qwe123qwe"
}

###
POST http://localhost/api/users
Content-Type: application/json

{
  "username": "admin",
  "user": "Test Admin User",
  "password": "qwe123qwe"
}

###
POST http://localhost/api/notes/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjRlYjU4MTIzYWQxMDQzYThjMjdmMjciLCJpYXQiOjE2NDkzMjY2MTF9.xD_XfZBEBi0StiSX9Mo_X7xK-i3hsPtbs3nwf-UB6hk

{
  "content": "fgd 234 fd fg df gdfg "
}

###

GET http://localhost/api/blogs
Accept: application/json

###
POST http://localhost/api/blogs/
Content-Type: application/json

{
  "title": "fgd 234 fd fg df gdfg ",
  "author": "fgd 234 fd fg df gdfg ",
  "url": "http://localhost"
}
